from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EasypaisaResponseCode(str, Enum):
    SUCCESS = "0000"
    SYSTEM_ERROR = "0001"
    REQUIRED_FIELD_MISSING = "0002"
    MERCHANT_ACCOUNT_NOT_ACTIVE = "0005"
    INVALID_STORE_ID = "0006"
    STORE_NOT_ACTIVE = "0007"
    PAYMENT_METHOD_NOT_ENABLED = "0008"
    INVALID_CREDENTIALS = "0010"
    LOW_BALANCE = "0013"
    ACCOUNT_DOES_NOT_EXIST = "0014"
    INVALID_TOKEN_EXPIRY = "0015"
    INVALID_EXPIRY = "0016"  # date should be future date


class EasyPaisaResponse(BaseModel):
    orderId: str = Field(
        ..., min_length=1, description="Merchant’s system generated Order ID"
    )
    storeId: int = Field(
        ge=0, description="Store ID generated during merchant registration in Easypaisa"
    )
    transactionDateTime: str = Field(
        ..., description="Format = dd/MM/yyyy hh:mm [AM/PM]"
    )
    responseCode: EasypaisaResponseCode = Field(
        ...,
        min_length=4,
        max_length=4,
        description="Easypaisa generated response codes",
    )
    responseDesc: str = Field(
        ..., min_length=3, description="Easypaisa generated response descriptions"
    )


class EasyPaisaMAResponse(EasyPaisaResponse):
    transactionId: str = Field(..., description="Transaction ID of Ericsson (EWP ID)")


class EasyPaisaOTCResponse(EasyPaisaResponse):
    paymentToken: str = Field(..., min_length=1, description="Token generated by OTC")
    paymentTokenExpiryDateTime: str = Field(
        ..., description="Format = dd/MM/yyyy hh:mm [AM/PM]"
    )


class EasyPaisaInquireTransactionResponse(EasyPaisaResponse):
    accountNum: str = Field(
        ..., min_length=1, description="Merchant’s EWP Account Number"
    )
    storeName: str = Field(..., description="Store Name")
    paymentToken: Optional[str] = Field(None, description="Token generated by OTC")
    transactionStatus: str = Field(..., description="The status of transaction")
    transactionAmount: str = Field(..., description="Total transaction amount ")
    paymentTokenExpiryDateTime: Optional[str] = Field(
        None, description="[Only For OTC] Format = dd/MM/yyyy hh:mm [AM/PM]"
    )
    msisdn: str = Field(..., description="Customer MSISDN")
    paymentMode: str = Field(..., description="Type of transaction: OTC, MA, CC")
